// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpXM7X99dJqveMnPY5atH8Pk7jF64OiwU',
    appId: '1:613091252826:android:9fb37540f5c5476e80d663',
    messagingSenderId: '613091252826',
    projectId: 'churchmanagementsystem-699c3',
    databaseURL: 'https://churchmanagementsystem-699c3-default-rtdb.firebaseio.com',
    storageBucket: 'churchmanagementsystem-699c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnjg6cNRz9ARH7kq54mGlaO5BceZPSTLM',
    appId: '1:613091252826:ios:1e77c3cda4be86b780d663',
    messagingSenderId: '613091252826',
    projectId: 'churchmanagementsystem-699c3',
    databaseURL: 'https://churchmanagementsystem-699c3-default-rtdb.firebaseio.com',
    storageBucket: 'churchmanagementsystem-699c3.appspot.com',
    androidClientId: '613091252826-vdgnfahgs5599qnp5sqk71rb1j663q7g.apps.googleusercontent.com',
    iosClientId: '613091252826-bmf6dp10hqjas3mdg5oam017hcedpr1e.apps.googleusercontent.com',
    iosBundleId: 'com.example.churchManagementSystem',
  );
}
